Level 0
infomediadesign/projektarbeit-ii-pixelgame-team03 pull request #23
Opened 2024-07-12 11:47 UTC by PaulaSeemann

2024-07-12 11:55 UTC, nino-tkalec requested changes
@PaulaSeemann Du musst noch die Ebenen anpassen

2024-07-14 15:04 UTC, nino-tkalec submitted a review, later dismissed

2024-07-14 15:31 UTC, E1kari requested changes
es werden 3 tilesets benuzt, das verwirrt den code.
Die biden tileatlasse bitte kombinieren und die tiles aus dem greyboxing in den tileatlas schmeißen, chat gpt meinte das geht irgendwie ohne alles neu zu platzieren ich hab aber keine Zeit das grad zu machen.

2024-07-17 15:20 UTC, nino-tkalec approved these changes

2024-08-05 17:51 UTC, E1kari approved these changes

2024-08-05 17:51 UTC, merged